### PR TITLE
Add Pixelmon x32 addon resource pack

### PR DESCRIPTION
**Pull request by EddyHg80**
I hope I did everything right :)

### CODE REVIEW

**Comment by RobertRR11** [comment]
Thanks for your addition to the mod list!

It doesn't work for me. But because we recently switched how the json is handled I'm not sure how to fix it.
@Juknum would need to look into it

**Comment by Juknum** [comment]
Can you replace "orgRepo" with "extRepo" and change the value from "EddyHg80" to "https://github.com/EddyHg80/pixelmon" ?

Everything else looks good to me :)

**Comment by EddyHg80** [comment]
I did the changes. Tell me if there's anything else I have to do.

Maybe you should update the "Add a new mod" page.

**Comment by Juknum** [comment]
Everything works!
> Just a little thing : can you remove the innitialcommit file in the 1.12.2 branch ? thx!

**Comment by RobertRR11** [comment]
> Maybe you should update the "Add a new mod" page.

Yeah, I am going to do that.

**Comment by EddyHg80** [comment]
Yep will do right now

**Pull request merged**
